/**
 * @description       : Test class to hold error messages for selector test methods.
 * @author            : Ben Learn
 * @last modified on  : 01-28-2023
 * @last modified by  : Ben Learn
**/
@isTest
public class TestErrorMessages {
    public static final String SOBJECT_FIELD_LIST_ERROR_MESSAGE = 'Expected prescribed field list.';
    public static final String SOBJECT_TYPE_ERROR_MESSAGE = 'Expected prescribed sObjectType.';
}
