/**
 * @description       : 
 * @author            : Ben Learn
 * @group             : 
 * @last modified on  : 02-25-2022
 * @last modified by  : Ben Learn
**/
public without sharing class RecommendedBadgeMixService {
    public static List<SetupDataWrapper> getSetupData() {
       // List<Mix_Category__c> mixCategories = [SELECT Name, Recommended_Badge_Mix__r.Name, (SELECT
         //   )]
        return null;
    }

    public class SetupDataWrapper {

    }
}
